// Catálogo Anava Importados
// Formato: [marca, linha, categoria, nome]
// A imagem de cada produto é buscada em img/products/<slug>.jpg
// (o slug é gerado a partir do nome — veja a página imagens.html para a lista completa)

const PRODUCTS = [
  // ============ MEDICUBE ============
  // Limpeza
  ["Medicube", "", "Limpeza", "Zero Foam Cleanser"],
  ["Medicube", "", "Limpeza", "PDRN Pink Gel Cleanser"],
  ["Medicube", "", "Limpeza", "PDRN Pink Whip Cleanser"],
  ["Medicube", "", "Limpeza", "Red Foam Cleanser"],
  // Toners
  ["Medicube", "", "Toner", "Zero Pore Toner"],
  ["Medicube", "", "Toner", "PDRN Pink Niacinamide Milky Toner"],
  ["Medicube", "", "Toner", "PDRN Pink CICA Soothing Toner"],
  ["Medicube", "", "Toner", "AGE-R Glutathione Glow Serum Toner"],
  ["Medicube", "", "Toner", "Exosome Cica Calming Toner"],
  // Toner Pads
  ["Medicube", "", "Toner Pads", "Zero Pore Pads"],
  ["Medicube", "", "Toner Pads", "Deep Vita C Pads"],
  ["Medicube", "", "Toner Pads", "PDRN Pink Collagen Toning Gel Pads"],
  ["Medicube", "", "Toner Pads", "Exosome Cica Calming Toner Pads"],
  ["Medicube", "", "Toner Pads", "Kojic Acid Toner Pads"],
  // Séruns
  ["Medicube", "", "Sérum", "Triple Collagen Serum"],
  ["Medicube", "", "Sérum", "PDRN Pink Peptide Serum"],
  ["Medicube", "", "Sérum", "PDRN Pink One Day Serum"],
  ["Medicube", "", "Sérum", "AGE-R Glutathione Glow Serum"],
  ["Medicube", "", "Sérum", "Deep Vita C Capsule Serum"],
  ["Medicube", "", "Sérum", "Deep Vita A Retinol Serum"],
  ["Medicube", "", "Sérum", "Red Serum"],
  ["Medicube", "", "Sérum", "TXA 15% Niacinamide Serum"],
  ["Medicube", "", "Sérum", "Collagen Glow Booster Serum"],
  // Exosome Shot
  ["Medicube", "Exosome Shot", "Sérum", "Zero Exosome Shot 7500"],
  ["Medicube", "Exosome Shot", "Sérum", "Zero Exosome Shot 2000"],
  ["Medicube", "Exosome Shot", "Sérum", "PDRN Pink Collagen Exosome Shot 2000"],
  ["Medicube", "Exosome Shot", "Sérum", "PDRN Pink Collagen Exosome Shot 7500"],
  // Cremes
  ["Medicube", "", "Creme", "Collagen Niacinamide Jelly Cream"],
  ["Medicube", "", "Creme", "Deep Vita C Capsule Cream"],
  ["Medicube", "", "Creme", "PDRN Pink Collagen Capsule Cream"],
  ["Medicube", "", "Creme", "PDRN Pink Peptide Cream"],
  ["Medicube", "", "Olhos", "PDRN Pink Peptide Eye Cream"],
  ["Medicube", "", "Olhos", "Deep Reviving Peptide Eye Cream"],
  ["Medicube", "", "Creme", "Triple Collagen Cream"],
  ["Medicube", "", "Creme", "Red Cream"],
  // Máscaras
  ["Medicube", "", "Máscara", "Collagen Night Wrapping Mask"],
  ["Medicube", "", "Máscara", "Salmon PDRN Pink Collagen Jelly Gel Mask"],
  ["Medicube", "", "Máscara", "Deep Vita C Mask"],
  ["Medicube", "", "Máscara", "PDRN Pink Vita Coating Sheet Mask"],
  ["Medicube", "", "Máscara", "PDRN Pink Caffeine Overnight Wrapping Mask"],
  ["Medicube", "", "Máscara", "Kojic Acid Gel Mask"],
  // Lábios
  ["Medicube", "", "Lábios", "PDRN Lip Sleeping Mask"],
  ["Medicube", "", "Lábios", "PDRN Lip Balm"],
  // Proteção Solar
  ["Medicube", "", "Proteção Solar", "No Cast Just Glow Collagen Sunscreen"],
  // Corpo
  ["Medicube", "", "Corpo & Banho", "Red Body Wash"],
  ["Medicube", "", "Corpo & Banho", "Hypochlorous Acid Body Serum"],
  ["Medicube", "", "Corpo & Banho", "Power Calming Spray"],
  // Aparelhos AGE-R
  ["Medicube", "AGE-R", "Aparelhos", "Booster Pro"],
  ["Medicube", "AGE-R", "Aparelhos", "Booster Pro X2"],
  ["Medicube", "AGE-R", "Aparelhos", "Booster Pro Heart Edition"],
  ["Medicube", "AGE-R", "Aparelhos", "Mini Booster Pro"],
  ["Medicube", "AGE-R", "Aparelhos", "Mini Booster Pro Plus"],
  ["Medicube", "AGE-R", "Aparelhos", "Derma EMS Shot"],
  ["Medicube", "AGE-R", "Aparelhos", "ATS Air Shot"],
  ["Medicube", "AGE-R", "Aparelhos", "Ussera Deep Shot"],
  ["Medicube", "AGE-R", "Aparelhos", "Booster-H"],
  ["Medicube", "AGE-R", "Aparelhos", "RF Ultra Tune 40.68"],

  // ============ SKIN1004 ============
  // Linha Centella Original
  ["SKIN1004", "Centella Original", "Limpeza", "Centella Light Cleansing Oil"],
  ["SKIN1004", "Centella Original", "Limpeza", "Centella Ampoule Foam"],
  ["SKIN1004", "Centella Original", "Toner", "Centella Toning Toner"],
  ["SKIN1004", "Centella Original", "Toner Pads", "Centella Quick Calming Pad"],
  ["SKIN1004", "Centella Original", "Sérum", "Centella Ampoule"],
  ["SKIN1004", "Centella Original", "Creme", "Centella Soothing Cream"],
  ["SKIN1004", "Centella Original", "Creme", "Centella Cream"],
  ["SKIN1004", "Centella Original", "Máscara", "Centella Watergel Sheet Ampoule Mask"],
  ["SKIN1004", "Centella Original", "Kits", "Centella Travel Kit"],
  ["SKIN1004", "Centella Original", "Kits", "Double Cleansing Duo"],
  // Linha Hyalu-Cica
  ["SKIN1004", "Hyalu-Cica", "Sérum", "Hyalu-Cica First Ampoule"],
  ["SKIN1004", "Hyalu-Cica", "Toner", "Hyalu-Cica Brightening Toner"],
  ["SKIN1004", "Hyalu-Cica", "Sérum", "Hyalu-Cica Blue Serum"],
  ["SKIN1004", "Hyalu-Cica", "Creme", "Hyalu-Cica Moisture Cream"],
  ["SKIN1004", "Hyalu-Cica", "Máscara", "Hyalu-Cica Sleeping Pack"],
  ["SKIN1004", "Hyalu-Cica", "Proteção Solar", "Hyalu-Cica Water-Fit Sun Serum SPF50+"],
  ["SKIN1004", "Hyalu-Cica", "Proteção Solar", "Hyalu-Cica Silky-Fit Sun Stick SPF50+"],
  ["SKIN1004", "Hyalu-Cica", "Mist", "Hyalu-Cica Cloudy Mist"],
  ["SKIN1004", "Hyalu-Cica", "Proteção Solar", "Hyalu-Cica Water-Fit Sun Stick Duo"],
  // Linha Tea-Trica
  ["SKIN1004", "Tea-Trica", "Sérum", "Tea-Trica Relief Ampoule"],
  ["SKIN1004", "Tea-Trica", "Toner", "Tea-Trica Purifying Toner"],
  ["SKIN1004", "Tea-Trica", "Limpeza", "Tea-Trica BHA Foam"],
  ["SKIN1004", "Tea-Trica", "Tratamentos", "Tea-Trica Spot Cream"],
  ["SKIN1004", "Tea-Trica", "Tratamentos", "Tea-Trica Spot Cover Patch"],
  ["SKIN1004", "Tea-Trica", "Máscara", "Tea-Trica Intensive Calming Mask"],
  ["SKIN1004", "Tea-Trica", "Kits", "Tea-Trica Relief Set"],
  // Linha Tone Brightening
  ["SKIN1004", "Tone Brightening", "Limpeza", "Tone Brightening Cleansing Gel Foam"],
  ["SKIN1004", "Tone Brightening", "Toner", "Tone Brightening Boosting Toner"],
  ["SKIN1004", "Tone Brightening", "Sérum", "Tone Brightening Capsule Ampoule"],
  ["SKIN1004", "Tone Brightening", "Creme", "Tone Brightening Capsule Cream"],
  ["SKIN1004", "Tone Brightening", "Proteção Solar", "Tone Brightening Tone-Up Sunscreen SPF50+"],
  // Linha Probio-Cica
  ["SKIN1004", "Probio-Cica", "Toner", "Probio-Cica Essence Toner"],
  ["SKIN1004", "Probio-Cica", "Sérum", "Probio-Cica Intensive Ampoule"],
  ["SKIN1004", "Probio-Cica", "Creme", "Probio-Cica Enrich Cream"],
  ["SKIN1004", "Probio-Cica", "Olhos", "Probio-Cica Bakuchiol Eye Cream"],
  ["SKIN1004", "Probio-Cica", "Proteção Solar", "Probio-Cica Glow Sun Ampoule SPF50+"],
  // Linha Poremizing
  ["SKIN1004", "Poremizing", "Limpeza", "Poremizing Deep Cleansing Foam"],
  ["SKIN1004", "Poremizing", "Toner", "Poremizing Clear Toner"],
  ["SKIN1004", "Poremizing", "Sérum", "Poremizing Fresh Ampoule"],
  ["SKIN1004", "Poremizing", "Creme", "Poremizing Light Gel Cream"],
  ["SKIN1004", "Poremizing", "Máscara", "Poremizing Quick Clay Stick Mask"],
  ["SKIN1004", "Poremizing", "Máscara", "Poremizing Fresh Clay Mask"],
  ["SKIN1004", "Poremizing", "Máscara", "Poremizing Pink Salt Mask"],
  // Linha Centella Teca
  ["SKIN1004", "Centella Teca", "Sérum", "Centella Teca Ampoule"],
  ["SKIN1004", "Centella Teca", "Creme", "Centella Teca Cream"],
  ["SKIN1004", "Centella Teca", "Toner", "Centella Teca Soothing Toner"],
  ["SKIN1004", "Centella Teca", "Máscara", "Centella Teca Intensive Soothing Mask"],
  ["SKIN1004", "Centella Teca", "Kits", "Centella Teca Routine Set"],
  // Linha Hyalu-Teca
  ["SKIN1004", "Hyalu-Teca", "Sérum", "Hyalu-Teca Plumping Ampoule"],
  ["SKIN1004", "Hyalu-Teca", "Creme", "Hyalu-Teca Glass Skin Milk"],
  ["SKIN1004", "Hyalu-Teca", "Creme", "Hyalu-Teca Firming Cream"],

  // ============ CELIMAX ============
  ["Celimax", "The Vita A", "Sérum", "The Vita A Retinal Shot Tightening Booster 15ml"],
  ["Celimax", "The Vita A", "Sérum", "The Vita A Retinol Shot Tightening 30ml"],
  ["Celimax", "Pore+ Dark Spot", "Creme", "Pore+ Dark Spot Brightening Cream 35ml"],
  ["Celimax", "Pore+ Dark Spot", "Toner Pads", "Pore+ Dark Spot Brightening Pads (40 un.)"],
  ["Celimax", "Pore+ Dark Spot", "Toner Pads", "Pore+ Dark Spot Brightening Pads (80 un.)"],
  ["Celimax", "The Real Noni", "Creme", "The Real Noni Energy Repair Cream 50ml"],
  ["Celimax", "The Real Noni", "Limpeza", "The Real Noni Acne Bubble Cleanser 155ml"],
  ["Celimax", "Pore+ Dark Spot", "Máscara", "Pore+ Dark Spot Brightening Cream Mask 20g"],
  ["Celimax", "Pore+ Dark Spot", "Sérum", "Pore+ Dark Spot Brightening Serum"],

  // ============ NUMBUZIN ============
  // No.1 – Linha Calmante
  ["Numbuzin", "No.1 Calmante", "Toner", "No.1 Pure-Full Calming Herb Toner"],
  ["Numbuzin", "No.1 Calmante", "Sérum", "No.1 Pure-Full Calming Herb Serum"],
  ["Numbuzin", "No.1 Calmante", "Creme", "No.1 Pure-Full Calming Water Cream"],
  ["Numbuzin", "No.1 Calmante", "Proteção Solar", "No.1 Clear Filter Sun Essence SPF50+ PA++++"],
  // No.2 – Linha Reparadora
  ["Numbuzin", "No.2 Reparadora", "Sérum", "No.2 Protein 43% Creamy Serum"],
  ["Numbuzin", "No.2 Reparadora", "Creme", "No.2 Cica Ceramide Repair Cream"],
  // No.3 – Linha Glow
  ["Numbuzin", "No.3 Glow", "Toner", "No.3 Super Glowing Essence Toner"],
  ["Numbuzin", "No.3 Glow", "Sérum", "No.3 Skin Softening Serum"],
  ["Numbuzin", "No.3 Glow", "Toner Pads", "No.3 Radiance Glowing Jumbo Essence Pad"],
  // No.4 – Linha Colágeno
  ["Numbuzin", "No.4 Colágeno", "Sérum", "No.4 Collagen 73% Pudding Serum"],
  ["Numbuzin", "No.4 Colágeno", "Creme", "No.4 Collagen Pudding Cream"],
  // No.5 – Linha Vitamina
  ["Numbuzin", "No.5 Vitamina", "Toner", "No.5 Vitamin Concentrated Toner"],
  ["Numbuzin", "No.5 Vitamina", "Sérum", "No.5 Vitamin Concentrated Serum"],
  ["Numbuzin", "No.5 Vitamina", "Creme", "No.5 Vitamin Concentrated Cream"],
  ["Numbuzin", "No.5 Vitamina", "Toner Pads", "No.5 Vitamin-Niacinamide Concentrated Pad"],
  ["Numbuzin", "No.5 Vitamina", "Máscara", "No.5 Vitamin Spotlight Sheet Mask"],
  // No.6 / No.8
  ["Numbuzin", "No.6", "Sérum", "No.6 Deep Sleep Mask Serum"],
  ["Numbuzin", "No.8", "Sérum", "No.8 Fine Cica Serum"],
  // No.9 NAD Bio Lifting
  ["Numbuzin", "No.9 NAD Bio Lifting", "Creme", "No.9 NAD Bio Lifting Cream"],
  ["Numbuzin", "No.9 NAD Bio Lifting", "Sérum", "No.9 NAD Bio Lifting Essence"],
  ["Numbuzin", "No.9 NAD Bio Lifting", "Olhos", "No.9 NAD Bio Lifting Eye Cream"],
  ["Numbuzin", "No.9 NAD Bio Lifting", "Máscara", "No.9 NAD Bio Lifting Full Cover Mask"],
  ["Numbuzin", "No.9 NAD Bio Lifting", "Sérum", "No.9 NAD Bio Lifting Retinal Shot"],
  // Limpeza
  ["Numbuzin", "", "Limpeza", "No.1 Easy Peasy Cleansing Oil"],
  ["Numbuzin", "", "Limpeza", "No.2 Deep Clean Fresh Cream Cleanser"],
  ["Numbuzin", "", "Limpeza", "No.3 Pore & Makeup Cleansing Balm"],
  // Máscaras
  ["Numbuzin", "", "Máscara", "No.1 Dewy Glow Spa Sheet Mask"],
  ["Numbuzin", "", "Máscara", "No.2 Water Collagen 65% Voluming Sheet Mask"],
  ["Numbuzin", "", "Máscara", "No.3 Tingle-Pore Softening Sheet Mask"],
  ["Numbuzin", "", "Máscara", "No.4 Icy Soothing Sheet Mask"],

  // ============ DR. ALTHEA ============
  // Cremes
  ["Dr. Althea", "", "Creme", "345 Relief Cream"],
  ["Dr. Althea", "", "Creme", "147 Barrier Cream"],
  ["Dr. Althea", "", "Creme", "Resveratrol 345NA Intensive Repair Cream"],
  ["Dr. Althea", "", "Creme", "Azulene 147HA Intensive Soothing Cream"],
  ["Dr. Althea", "", "Olhos", "To Be Youthful Eye Serum"],
  // Séruns
  ["Dr. Althea", "", "Sérum", "345 Relief Serum"],
  ["Dr. Althea", "", "Sérum", "15% Niacinamide Purity Serum"],
  ["Dr. Althea", "", "Sérum", "Vitamin C Boosting Serum"],
  ["Dr. Althea", "", "Sérum", "ABC Glow Whipped Serum"],
  ["Dr. Althea", "", "Sérum", "0.1 Gentle Retinol Serum"],
  // Limpadores
  ["Dr. Althea", "", "Limpeza", "Amino Acid Gentle Bubble Cleanser"],
  ["Dr. Althea", "", "Limpeza", "Green Relief Amino Gel Cleanser"],
  ["Dr. Althea", "", "Limpeza", "Gentle Pore Vegan Cleansing Oil"],
  ["Dr. Althea", "", "Limpeza", "Pure Grinding Cleansing Balm"],
  ["Dr. Althea", "", "Limpeza", "Pore Refresh Grinding Cleansing Balm"],
  // Mists
  ["Dr. Althea", "", "Mist", "345 Relief Cream Mist"],
  ["Dr. Althea", "", "Mist", "Vita Glow Cream Mist"],
  // Máscaras
  ["Dr. Althea", "", "Máscara", "Aqua Blue Hydration Mask"],
  ["Dr. Althea", "", "Máscara", "Herb Therapy Velvet Mask"],
  ["Dr. Althea", "", "Máscara", "Oasis Soothing Mask"],
  ["Dr. Althea", "", "Máscara", "Marine Anti-Blemish Mask"],
  ["Dr. Althea", "", "Máscara", "Jelly Seal Repair Mask"],
  ["Dr. Althea", "", "Máscara", "Jelly Seal Dewy Mask"],
  ["Dr. Althea", "", "Máscara", "Vitamin Brightening Mask"],
  // Tratamentos
  ["Dr. Althea", "", "Tratamentos", "15% Calamine Spot Powder"],
  // Protetores solares
  ["Dr. Althea", "", "Proteção Solar", "Aqua Glowing Sunscreen SPF50+ PA++++"],
  ["Dr. Althea", "", "Proteção Solar", "Green Tea Fresh Sunscreen SPF50+ PA+++"],

  // ============ ANUA ============
  // Limpeza
  ["Anua", "", "Limpeza", "Heartleaf Pore Control Cleansing Oil"],
  ["Anua", "", "Limpeza", "Heartleaf Quercetinol Pore Deep Cleansing Foam"],
  ["Anua", "", "Limpeza", "Heartleaf Succinic Moisture Cleansing Foam"],
  ["Anua", "", "Limpeza", "8 Hyaluronic Acid Hydrating Gentle Foaming Cleanser"],
  ["Anua", "", "Limpeza", "8 Hyaluronic Acid Moisturizing Gentle Gel Cleanser"],
  ["Anua", "", "Limpeza", "Rice Enzyme Brightening Cleansing Powder"],
  // Tônicos
  ["Anua", "", "Toner", "Heartleaf 77 Soothing Toner"],
  ["Anua", "", "Toner", "Rice 70 Glow Milky Toner"],
  ["Anua", "", "Toner", "Peach 77 Niacin Essence Toner"],
  ["Anua", "", "Toner", "Azelaic 3 Cica Skin Clarifying Toner"],
  ["Anua", "", "Toner", "BHA 2% Gentle Exfoliating Toner"],
  // Séruns e Ampoules
  ["Anua", "", "Sérum", "Heartleaf 80 Moisture Soothing Ampoule"],
  ["Anua", "", "Sérum", "Heartleaf 80 Moisture Soothing Ampoule EX"],
  ["Anua", "", "Sérum", "Peach 70 Niacin Serum"],
  ["Anua", "", "Sérum", "Niacinamide 10% + TXA 4% Serum"],
  ["Anua", "", "Sérum", "Rice Ceramide 7 Hydrating Barrier Serum"],
  ["Anua", "", "Sérum", "Azelaic Acid 10 Hyaluron Redness Soothing Serum"],
  ["Anua", "", "Sérum", "PDRN Hyaluronic Acid Capsule 100 Serum"],
  ["Anua", "", "Sérum", "Retinol 0.3% + Niacin Renewing Serum"],
  // Cremes e Hidratantes
  ["Anua", "", "Creme", "Heartleaf 70 Daily Lotion"],
  ["Anua", "", "Creme", "Heartleaf 70 Intense Calming Cream"],
  ["Anua", "", "Creme", "Peach 77 Niacin Enriched Cream"],
  ["Anua", "", "Creme", "3 Ceramide Panthenol Moisture Barrier Cream"],
  ["Anua", "", "Creme", "Azelaic Acid CICA Skin Soothing Moisturizer"],
  ["Anua", "", "Creme", "PDRN Hyaluronic Acid Cream"],
  ["Anua", "", "Creme", "Collagen Retinol Refining Gua Sha Cream"],
  // Pads
  ["Anua", "", "Toner Pads", "Heartleaf 77 Clear Pad"],
  ["Anua", "", "Toner Pads", "Heartleaf 77 Toner Pad"],
  ["Anua", "", "Toner Pads", "Peach Niacin Brightening Pad"],
  ["Anua", "", "Toner Pads", "8 Hyaluronic Acid Catechin Calming Pad"],
  ["Anua", "", "Toner Pads", "Azelaic 10 Hyaluron Redness Soothing Pad"],
  // Máscaras
  ["Anua", "", "Máscara", "Heartleaf Soothing Sheet Mask"],
  ["Anua", "", "Máscara", "Peach Niacin Brightening Mask"],
  ["Anua", "", "Máscara", "Rice 70 Glow Collagen Mask"],
  ["Anua", "", "Máscara", "Birch Moisture Sheet Mask"],
  // Protetores solares
  ["Anua", "", "Proteção Solar", "Heartleaf Silky Moisture Sun Cream SPF50+ PA++++"],
  ["Anua", "", "Proteção Solar", "Airy Sun Cream SPF50+ PA++++"],
  ["Anua", "", "Proteção Solar", "Airy Sun Stick SPF50+ PA++++"],
  // Tratamentos
  ["Anua", "", "Tratamentos", "Heartleaf Spot Patch"],
  ["Anua", "", "Tratamentos", "Heartleaf Spot Gel"],

  // ============ BEAUTY OF JOSEON ============
  // Limpeza
  ["Beauty of Joseon", "", "Limpeza", "Radiance Cleansing Balm"],
  ["Beauty of Joseon", "", "Limpeza", "Ginseng Cleansing Oil"],
  ["Beauty of Joseon", "", "Limpeza", "Green Plum Refreshing Cleanser"],
  ["Beauty of Joseon", "", "Toner", "Green Plum Refreshing Toner"],
  // Essências e Tônicos
  ["Beauty of Joseon", "", "Toner", "Ginseng Essence Water"],
  ["Beauty of Joseon", "", "Toner", "Glow Replenishing Rice Milk"],
  // Séruns
  ["Beauty of Joseon", "", "Sérum", "Glow Serum: Propolis + Niacinamide"],
  ["Beauty of Joseon", "", "Sérum", "Glow Deep Serum: Rice + Alpha-Arbutin"],
  ["Beauty of Joseon", "", "Sérum", "Revive Serum: Ginseng + Snail Mucin"],
  ["Beauty of Joseon", "", "Sérum", "Calming Serum: Green Tea + Panthenol"],
  ["Beauty of Joseon", "", "Sérum", "Light On Serum: Centella + Vitamin C"],
  // Olhos
  ["Beauty of Joseon", "", "Olhos", "Revive Eye Serum: Ginseng + Retinal"],
  // Cremes
  ["Beauty of Joseon", "", "Creme", "Dynasty Cream"],
  ["Beauty of Joseon", "", "Creme", "Red Bean Water Gel"],
  // Máscaras
  ["Beauty of Joseon", "", "Máscara", "Red Bean Refreshing Pore Mask"],
  ["Beauty of Joseon", "", "Máscara", "Ground Rice and Honey Glow Mask"],
  // Protetores Solares
  ["Beauty of Joseon", "", "Proteção Solar", "Relief Sun: Rice + Probiotics SPF50+ PA++++"],
  ["Beauty of Joseon", "", "Proteção Solar", "Relief Sun Aqua-Fresh: Rice + B5 SPF50+ PA++++"],
  ["Beauty of Joseon", "", "Proteção Solar", "Matte Sun Stick: Mugwort + Camelia SPF50+ PA++++"],

  // ============ KERASYS (Linha Capilar) ============
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Moisturizing Shampoo"],
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Moisturizing Conditioner"],
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Repairing Shampoo"],
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Repairing Conditioner"],
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Revitalizing Shampoo"],
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Revitalizing Conditioner"],
  ["Kerasys", "Hair Clinic", "Cabelo", "Hair Clinic Serum"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Keratin Deep Repair Shampoo"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Keratin Deep Repair Conditioner"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Keratin Deep Repair Treatment"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Volume Clinic Shampoo"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Volume Clinic Conditioner"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Double Care Shampoo"],
  ["Kerasys", "Advanced", "Cabelo", "Advanced Double Care Conditioner"],
  ["Kerasys", "Keramide", "Cabelo", "Keramide Ampoule Damage Clinic Shampoo"],
  ["Kerasys", "Keramide", "Cabelo", "Keramide Ampoule Damage Clinic Conditioner"],
  ["Kerasys", "Keramide", "Cabelo", "Keramide Ampoule Damage Clinic Treatment"],
  ["Kerasys", "Keramide", "Cabelo", "Keramide Hair Clinic Serum"],
  ["Kerasys", "Keramide", "Cabelo", "Keramide Heat Protection Clinic Treatment"],
  ["Kerasys", "Keramide", "Cabelo", "Keramide Ampoule Frizz Care Mask"],
  ["Kerasys", "Oriental Premium", "Cabelo", "Oriental Premium Shampoo"],
  ["Kerasys", "Oriental Premium", "Cabelo", "Oriental Premium Conditioner"],
  ["Kerasys", "Oriental Premium", "Cabelo", "Oriental Premium Treatment"],
  ["Kerasys", "Oriental Premium", "Cabelo", "Oriental Premium Hair Oil"],
  ["Kerasys", "Propolis", "Cabelo", "Propolis Hair Bonding Pro Repair Shampoo"],
  ["Kerasys", "Propolis", "Cabelo", "Propolis Hair Bonding Pro Repair Treatment"],
  ["Kerasys", "Propolis", "Cabelo", "Propolis Hair Bonding No Wash Repair Treatment"],
  ["Kerasys", "Propolis", "Cabelo", "Propolis Energy & Shine Shampoo"],
  ["Kerasys", "Propolis", "Cabelo", "Propolis Energy & Shine Treatment"],
  ["Kerasys", "Argan Oil", "Cabelo", "Argan Oil Shampoo"],
  ["Kerasys", "Argan Oil", "Cabelo", "Argan Oil Conditioner"],
  ["Kerasys", "Argan Oil", "Cabelo", "Argan Oil Hair Serum"],
  ["Kerasys", "Argan Oil", "Cabelo", "Argan Oil Hair Mask"],
  ["Kerasys", "Coconut Oil", "Cabelo", "Coconut Oil Shampoo"],
  ["Kerasys", "Coconut Oil", "Cabelo", "Coconut Oil Conditioner"],
  ["Kerasys", "Coconut Oil", "Cabelo", "Coconut Oil Hair Mask"],
  ["Kerasys", "Perfumed", "Cabelo", "Elegance Shampoo"],
  ["Kerasys", "Perfumed", "Cabelo", "Elegance Conditioner"],
  ["Kerasys", "Perfumed", "Cabelo", "Romantic Shampoo"],
  ["Kerasys", "Perfumed", "Cabelo", "Romantic Conditioner"],
  ["Kerasys", "Perfumed", "Cabelo", "Glamour Shampoo"],
  ["Kerasys", "Perfumed", "Cabelo", "Glamour Conditioner"],
  ["Kerasys", "Perfumed", "Cabelo", "Charm Shampoo"],
  ["Kerasys", "Perfumed", "Cabelo", "Charm Conditioner"],
  ["Kerasys", "Perfumed", "Cabelo", "Fleur Shampoo"],
  ["Kerasys", "Perfumed", "Cabelo", "Fleur Conditioner"],
  ["Kerasys", "Derma & More", "Cabelo", "Derma & More Cera Shampoo"],
  ["Kerasys", "Derma & More", "Cabelo", "Derma & More Cera Conditioner"],
  ["Kerasys", "Derma & More", "Cabelo", "Derma & More Cica Shampoo"],
  ["Kerasys", "Derma & More", "Cabelo", "Derma & More Cica Conditioner"],
  ["Kerasys", "Derma & More", "Cabelo", "Derma & More AHA Shampoo"],
  ["Kerasys", "Derma & More", "Cabelo", "Derma & More AHA Conditioner"],
  ["Kerasys", "Scalp Care", "Cabelo", "Scalp Care Shampoo (Couro Cabeludo Oleoso)"],
  ["Kerasys", "Scalp Care", "Cabelo", "Scalp Care Shampoo (Couro Cabeludo Seco)"],
  ["Kerasys", "Scalp Care", "Cabelo", "Scalp Care Conditioner"],

  // ============ TSUBAKI ============
  ["Tsubaki", "Premium Moist & Repair", "Cabelo", "Premium Moist & Repair Shampoo"],
  ["Tsubaki", "Premium Moist & Repair", "Cabelo", "Premium Moist & Repair Conditioner"],
  ["Tsubaki", "Premium Moist & Repair", "Cabelo", "Premium Moist & Repair Treatment"],
  ["Tsubaki", "Premium Repair", "Cabelo", "Premium Repair Shampoo"],
  ["Tsubaki", "Premium Repair", "Cabelo", "Premium Repair Conditioner"],
  ["Tsubaki", "Premium Repair", "Cabelo", "Premium Repair Treatment"],
  ["Tsubaki", "Premium Volume & Repair", "Cabelo", "Premium Volume & Repair Shampoo"],
  ["Tsubaki", "Premium Volume & Repair", "Cabelo", "Premium Volume & Repair Conditioner"],
  ["Tsubaki", "Premium Volume & Repair", "Cabelo", "Premium Volume & Repair Treatment"],
  ["Tsubaki", "Premium EX", "Cabelo", "Premium EX Intensive Repair Shampoo"],
  ["Tsubaki", "Premium EX", "Cabelo", "Premium EX Intensive Repair Treatment"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Premium Repair Hair Mask"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Premium EX Repair Mask"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Premium Treatment Water"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Hair Oil Force"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Premium Hair Oil"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Hair Milk"],
  ["Tsubaki", "Tratamentos Especiais", "Cabelo", "Hair Serum"],

  // ============ &HONEY ============
  ["&honey", "Deep Moist", "Cabelo", "Deep Moist Shampoo 1.0"],
  ["&honey", "Deep Moist", "Cabelo", "Deep Moist Hair Treatment 2.0"],
  ["&honey", "Deep Moist", "Cabelo", "Deep Moist Hair Oil 3.0"],
  ["&honey", "Deep Moist", "Cabelo", "Deep Moist Hair Pack 1.5"],
  ["&honey", "Melty", "Cabelo", "Melty Moist Repair Shampoo 1.0"],
  ["&honey", "Melty", "Cabelo", "Melty Moist Repair Hair Treatment 2.0"],
  ["&honey", "Melty", "Cabelo", "Melty Moist Repair Hair Oil 3.0"],
  ["&honey", "Melty", "Cabelo", "Melty Moist Repair Hair Pack 1.5"],
  ["&honey", "Silky", "Cabelo", "Silky Smooth Moist Shampoo 1.0"],
  ["&honey", "Silky", "Cabelo", "Silky Smooth Moist Hair Treatment 2.0"],
  ["&honey", "Silky", "Cabelo", "Silky Smooth Moist Hair Oil 3.0"],
  ["&honey", "Silky", "Cabelo", "Silky Smooth Hair Pack 1.5"],
  ["&honey", "Creamy EX", "Cabelo", "Creamy EX Damage Repair Shampoo 1.0"],
  ["&honey", "Creamy EX", "Cabelo", "Creamy EX Damage Repair Hair Treatment 2.0"],
  ["&honey", "Creamy EX", "Cabelo", "Creamy EX Damage Repair Hair Oil 3.0"],
  ["&honey", "Creamy EX", "Cabelo", "Creamy EX Damage Repair Hair Mask"],

  // ============ MISE EN SCÈNE ============
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Original"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Super Rich"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Styling"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Rose Perfume"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Coco Water"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Wonder Bubble Shampoo"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Original Shampoo"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Original Conditioner"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Treatment"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Hair Mask"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Mist"],
  ["Mise en Scène", "Perfect Serum", "Cabelo", "Perfect Serum Rinse"],
  ["Mise en Scène", "Damage Care", "Cabelo", "Damage Care Shampoo"],
  ["Mise en Scène", "Damage Care", "Cabelo", "Damage Care Conditioner"],
  ["Mise en Scène", "Damage Care", "Cabelo", "Damage Care Treatment"],
  ["Mise en Scène", "Aging Care", "Cabelo", "Aging Care Shampoo"],
  ["Mise en Scène", "Aging Care", "Cabelo", "Aging Care Conditioner"],
  ["Mise en Scène", "Aging Care", "Cabelo", "Aging Care Treatment"],
  ["Mise en Scène", "Scalp Care", "Cabelo", "Scalp Care Shampoo"],
  ["Mise en Scène", "Scalp Care", "Cabelo", "Scalp Care Conditioner"],
  ["Mise en Scène", "Scalp Care", "Cabelo", "Scalp Care Scaler"],
  ["Mise en Scène", "Scalp Care", "Cabelo", "Scalp Care Tonic"],
  ["Mise en Scène", "Hello Bubble", "Cabelo", "Hello Bubble Hair Color (todas as tonalidades)"],
  ["Mise en Scène", "Styling", "Cabelo", "Power Swing Hair Wax"],
  ["Mise en Scène", "Styling", "Cabelo", "Perfect Styling Serum"],
  ["Mise en Scène", "Styling", "Cabelo", "Curling Essence 2X"],
  ["Mise en Scène", "Styling", "Cabelo", "Strong Hold Hair Spray"],

  // ============ VICTORIA'S SECRET ============
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Bare Vanilla"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Bare Vanilla Cashmere"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Bare Vanilla Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Coconut Passion"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Coconut Passion Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Love Spell"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Love Spell Cashmere"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Love Spell Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Pure Seduction"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Pure Seduction Cashmere"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Pure Seduction Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Velvet Petals"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Velvet Petals Cashmere"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Velvet Petals Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Aqua Kiss"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Aqua Kiss Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Midnight Bloom"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Midnight Bloom Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Amber Romance"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Amber Romance Shimmer"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Temptation"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Mango Temptation"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Pear Glacé"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Strawberries & Champagne"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Romantic"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Secret Charm"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Rush"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Passion Struck"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Endless Love"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Moon Spiced Apple"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Noir Tease"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Velvet Petals Sol"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Love Spell Sol"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Pure Seduction Sol"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Bare Vanilla Sol"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Velvet Petals Splash"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Pure Seduction Splash"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Love Spell Splash"],
  ["Victoria's Secret", "Body Splash", "Perfumaria", "Bare Vanilla Splash"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Bombshell Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Bombshell Intense Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Bombshell Passion Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Bombshell Escape Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Tease Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Tease Crème Cloud Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Tease Candy Noir Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Very Sexy Fragrance Mist"],
  ["Victoria's Secret", "Fragrance Mist", "Perfumaria", "Heavenly Fragrance Mist"],

  // ============ BATH & BODY WORKS ============
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Ariel Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Belle Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Cinderella Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Jasmine Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Moana Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Tiana Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Life's a Fairytale Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Aurora Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Mulan Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Rapunzel Fine Fragrance Mist"],
  ["Bath & Body Works", "Linha Princesas", "Perfumaria", "Snow White Fine Fragrance Mist"],

  // ============ NEECHE HOUSE ============
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Sweetmallow"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Altaro"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Pink Flames"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Flames"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Exotic"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "White Latte"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Anjos"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Dalena"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Summer Heaven"],
  ["Neeche House", "Hidratantes", "Corpo & Banho", "Summer Paradise"],

  // ============ OMG ============
  ["OMG", "", "Limpeza", "Pore Control Cleansing Oil"],
  ["OMG", "", "Limpeza", "Rice Stick Cleanser"],
  ["OMG", "", "Limpeza", "Calamine Stick Cleanser"],
  ["OMG", "", "Limpeza", "Pumpkin Stick Cleanser"],
  ["OMG", "", "Proteção Solar", "PDRN Collagen Stick Sunscreen SPF50+"],
  ["OMG", "", "Máscara", "Collagen Mask"],
  ["OMG", "", "Máscara", "Ceramide Mask"],
  ["OMG", "", "Máscara", "Hyaluronic Acid Mask"],
  ["OMG", "", "Máscara", "Peptide Mask"],
  ["OMG", "", "Máscara", "Vitamin Mask"],
  ["OMG", "", "Sérum", "Vitamin C Serum"],
  ["OMG", "", "Sérum", "Niacinamide Serum"],
  ["OMG", "", "Sérum", "Hyaluronic Acid Serum"],
  ["OMG", "", "Sérum", "PDRN Serum"],
  ["OMG", "", "Creme", "Collagen Cream"],
  ["OMG", "", "Creme", "Ceramide Cream"],
  ["OMG", "", "Creme", "Peptide Cream"],
  ["OMG", "", "Olhos", "Eye Cream"],
  ["OMG", "", "Proteção Solar", "Sunscreen Stick SPF50+"],
];
